system-ghc: false

# ghc 8.4.4
#resolver: lts-12.16

# ghc 8.6.1
#resolver: nightly-2018-10-03

# Lutris
resolver: nightly-2024-02-27

# Local packages, usually specified by relative directory name
packages:
- '.'
# - ../flat

flags:
   serialise:
     newtime15: true

extra-deps:
- datasets-0.4.0
- packman-0.5.0
- persist-0.1.1.5
- streaming-cassava-0.2.0.0
allow-newer: true
